In [3]:
import pandas as pd
import numpy as np
import os
import sys

In [4]:
ROOT_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

In [5]:
raw_data_path = os.path.join(ROOT_DIR, "data", "raw", "det_val_hr_2024_12.csv.gz")
df = pd.read_csv(raw_data_path, sep=";", compression="gzip", low_memory=False)
print(df.info())
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\Study\\HWR Berlin\\Semester 2\\Enterprise Architecture for Big Data\\0. Big Data Group Project\\Git\\berlin-traffic-dashboard\\data\\raw\\det_val_hr_2024_12.csv.gz'

In [ ]:
df["qualitaet"].value_counts()

qualitaet
1.00    166479
0.92     25627
0.83     11101
0.75      6937
Name: count, dtype: int64

In [ ]:
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)
from scripts.processor.kpi_loader import TrafficKPILoader
from scripts.processor.enricher import TrafficDataEnricher

In [ ]:
# Load KPI
kpi_path = os.path.join(ROOT_DIR, "src","data", "raw","2024","det_val_hr_2024_12.csv.gz")
kpi_loader = TrafficKPILoader(kpi_path)
df_kpi = kpi_loader.load()
df_kpi

,detid_15,tag,qualitaet,q_kfz_det_hr,v_kfz_det_hr,q_pkw_det_hr,v_pkw_det_hr,q_lkw_det_hr,v_lkw_det_hr,hour
0,100101010000167,2024-12-30,1.0,114,69,103,69,11,70,6
1,100101010000167,2024-12-30,1.0,134,71,126,71,8,71,7
2,100101010000167,2024-12-30,1.0,160,65,151,65,9,65,8
3,100101010000167,2024-12-30,1.0,304,60,298,60,6,58,9
4,100101010000167,2024-12-30,1.0,440,61,428,61,12,64,10
...,...,...,...,...,...,...,...,...,...,...
210139,100101010093329,2024-12-31,1.0,151,32,149,32,2,28,19
210140,100101010093329,2024-12-31,1.0,168,30,162,31,6,28,20
210141,100101010093329,2024-12-31,1.0,140,36,138,36,2,28,21
210142,100101010093329,2024-12-31,1.0,140,35,139,35,1,35,22
210143,100101010093329,2024-12-31,1.0,100,36,100,36,0,-1,23

In [ ]:
meta_path = os.path.join(ROOT_DIR, "src","data", "raw", "Stammdaten_Verkehrsdetektion_2022_07_20.xlsx")
enricher = TrafficDataEnricher(df_kpi, meta_path)
df_enriched = enricher.enrich()
df_enriched

,detid_15,tag,qualitaet,q_kfz_det_hr,v_kfz_det_hr,q_pkw_det_hr,v_pkw_det_hr,q_lkw_det_hr,v_lkw_det_hr,hour,...,SPUR,annotation,LÄNGE (WGS84),BREITE (WGS84),INBETRIEBNAHME,ABBAUDATUM,DEINSTALLIERT,KOMMENTAR,lon,lat
0,100101010000167,2024-12-30,1.0,114,69,103,69,11,70,6,...,HF_R,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868
1,100101010000167,2024-12-30,1.0,134,71,126,71,8,71,7,...,HF_R,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868
2,100101010000167,2024-12-30,1.0,160,65,151,65,9,65,8,...,HF_R,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868
3,100101010000167,2024-12-30,1.0,304,60,298,60,6,58,9,...,HF_R,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868
4,100101010000167,2024-12-30,1.0,440,61,428,61,12,64,10,...,HF_R,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223527,100101010093329,2024-12-31,1.0,151,32,149,32,2,28,19,...,HF_R,Hauptfahrbahn rechte Spur,13.387089,52.531362,2016-09-04,NaT,NaN,NaN,13.387089,52.531362
223528,100101010093329,2024-12-31,1.0,168,30,162,31,6,28,20,...,HF_R,Hauptfahrbahn rechte Spur,13.387089,52.531362,2016-09-04,NaT,NaN,NaN,13.387089,52.531362
223529,100101010093329,2024-12-31,1.0,140,36,138,36,2,28,21,...,HF_R,Hauptfahrbahn rechte Spur,13.387089,52.531362,2016-09-04,NaT,NaN,NaN,13.387089,52.531362
223530,100101010093329,2024-12-31,1.0,140,35,139,35,1,35,22,...,HF_R,Hauptfahrbahn rechte Spur,13.387089,52.531362,2016-09-04,NaT,NaN,NaN,13.387089,52.531362
223531,100101010093329,2024-12-31,1.0,100,36,100,36,0,-1,23,...,HF_R,Hauptfahrbahn rechte Spur,13.387089,52.531362,2016-09-04,NaT,NaN,NaN,13.387089,52.531362

In [ ]:
df_enriched[["q_kfz_det_hr"]].describe()
print(df_enriched.columns)
df_enriched[df_enriched["q_kfz_det_hr"]>1000][["q_kfz_det_hr",'q_pkw_det_hr','q_lkw_det_hr','tag','hour','STRASSE']]

Index(['detid_15', 'tag', 'qualitaet', 'q_kfz_det_hr', 'v_kfz_det_hr',
       'q_pkw_det_hr', 'v_pkw_det_hr', 'q_lkw_det_hr', 'v_lkw_det_hr', 'hour',
       'MQ_KURZNAME', 'DET_NAME_ALT', 'DET_NAME_NEU', 'MQ_ID15', 'STRASSE',
       'POSITION', 'POS_DETAIL', 'RICHTUNG', 'SPUR', 'annotation',
       'LÄNGE (WGS84)', 'BREITE (WGS84)', 'INBETRIEBNAHME', 'ABBAUDATUM',
       'DEINSTALLIERT', 'KOMMENTAR', 'lon', 'lat'],
      dtype='object')

,q_kfz_det_hr,q_pkw_det_hr,q_lkw_det_hr,tag,hour,STRASSE
5456,1115,1110,5,2024-12-11,17,Mariendorfer Damm
17885,1424,1374,50,2024-12-25,19,Seestraße
17886,1720,1720,0,2024-12-25,20,Seestraße
17888,1132,1102,30,2024-12-25,22,Seestraße
17901,1059,1007,52,2024-12-29,20,Seestraße
...,...,...,...,...,...,...
147357,1252,564,688,2024-12-08,10,Silbersteinstraße
147358,1163,377,785,2024-12-08,11,Silbersteinstraße
147359,1193,543,650,2024-12-08,12,Silbersteinstraße
147360,1227,754,473,2024-12-08,13,Silbersteinstraße
147361,1125,713,412,2024-12-08,14,Silbersteinstraße

In [ ]:
# df_enriched.to_parquet("data/processed/kpi_enriched_dec_2024.parquet", index=False)

In [ ]:
osm_data_path = os.path.join(ROOT_DIR, "data", "osm", "berlin_drive.graphml")
from scripts.processor.osm_matcher import StreetMatcher
osm_data = StreetMatcher(osm_data_path)
osm_gdf = osm_data._to_geo(df_enriched)
print(osm_gdf.columns)
osm_gdf.info()
osm_gdf.head()

Index(['detid_15', 'tag', 'qualitaet', 'q_kfz_det_hr', 'v_kfz_det_hr',
       'q_pkw_det_hr', 'v_pkw_det_hr', 'q_lkw_det_hr', 'v_lkw_det_hr', 'hour',
       'MQ_KURZNAME', 'DET_NAME_ALT', 'DET_NAME_NEU', 'MQ_ID15', 'STRASSE',
       'POSITION', 'POS_DETAIL', 'RICHTUNG', 'SPUR', 'annotation',
       'LÄNGE (WGS84)', 'BREITE (WGS84)', 'INBETRIEBNAHME', 'ABBAUDATUM',
       'DEINSTALLIERT', 'KOMMENTAR', 'lon', 'lat', 'geometry'],
      dtype='object')
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 223532 entries, 0 to 223531
Data columns (total 29 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   detid_15        223532 non-null  int64
 1   tag             223532 non-null  datetime64[ns]
 2   qualitaet       223532 non-null  float64
 3   q_kfz_det_hr    223532 non-null  int64
 4   v_kfz_det_hr    223532 non-null  int64
 5   q_pkw_det_hr    223532 non-null  int64
 6   v_pkw_det_hr    223532 non-null  int64
 7   q_lkw_det_hr    223532 non-null  int64
 8   v_lkw_det_hr    223532 non-null  int64
 9   hour            223532 non-null  int64
 10  MQ_KURZNAME     223532 non-null  object
 11  DET_NAME_ALT    223532 non-null  object
 12  DET_NAME_NEU    223532 non-null  object
 13  MQ_ID15         223532 non-null  int64
 14  STRASSE         223532 non-null  object
 15  POSITION        223532 non-null  object
 16  POS_DETAIL      211174 non-null  object
 17  RICHTUNG        223532 non-null  object
 18  SPUR            223532 non-null  object
 19  annotation      223532 non-null  object
 20  LÄNGE (WGS84)   223532 non-null  float64
 21  BREITE (WGS84)  223532 non-null  float64
 22  INBETRIEBNAHME  223532 non-null  datetime64[ns]
 23  ABBAUDATUM      0 non-null       datetime64[ns]
 24  DEINSTALLIERT   6690 non-null    object
 25  KOMMENTAR       6690 non-null    object
 26  lon             223532 non-null  float64
 27  lat             223532 non-null  float64
 28  geometry        223532 non-null  geometry
dtypes: datetime64[ns](3), float64(5), geometry(1), int64(9), object(11)
memory usage: 49.5+ MB

,detid_15,tag,qualitaet,q_kfz_det_hr,v_kfz_det_hr,q_pkw_det_hr,v_pkw_det_hr,q_lkw_det_hr,v_lkw_det_hr,hour,...,annotation,LÄNGE (WGS84),BREITE (WGS84),INBETRIEBNAHME,ABBAUDATUM,DEINSTALLIERT,KOMMENTAR,lon,lat,geometry
0,100101010000167,2024-12-30,1.0,114,69,103,69,11,70,6,...,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868,POINT (13.19258 52.43387)
1,100101010000167,2024-12-30,1.0,134,71,126,71,8,71,7,...,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868,POINT (13.19258 52.43387)
2,100101010000167,2024-12-30,1.0,160,65,151,65,9,65,8,...,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868,POINT (13.19258 52.43387)
3,100101010000167,2024-12-30,1.0,304,60,298,60,6,58,9,...,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868,POINT (13.19258 52.43387)
4,100101010000167,2024-12-30,1.0,440,61,428,61,12,64,10,...,Hauptfahrbahn rechte Spur,13.192578,52.433868,2003-02-18,NaT,NaN,NaN,13.192578,52.433868,POINT (13.19258 52.43387)

In [ ]:
import osmnx as ox
G = ox.load_graphml(osm_data_path)
osm_edges = ox.graph_to_gdfs(G, nodes=False)
osm_edges = osm_edges[osm_edges["geometry"].notnull()]
osm_edges.reset_index(drop=True, inplace=True)
osm_edges["osm_id_index"] = osm_edges.index

In [ ]:
crs_proj = "EPSG:32633"
osm_edges_proj = osm_edges.to_crs(crs_proj)
osm_edges_proj.info()
osm_edges_proj.head()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 73332 entries, 0 to 73331
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   osmid         73332 non-null  object
 1   highway       73332 non-null  object
 2   lanes         22910 non-null  object
 3   maxspeed      68109 non-null  object
 4   name          72009 non-null  object
 5   oneway        73332 non-null  bool
 6   reversed      73332 non-null  object
 7   length        73332 non-null  float64
 8   geometry      73332 non-null  geometry
 9   width         13505 non-null  object
 10  ref           1965 non-null   object
 11  bridge        932 non-null    object
 12  tunnel        281 non-null    object
 13  junction      186 non-null    object
 14  access        869 non-null    object
 15  area          5 non-null      object
 16  service       2 non-null      object
 17  est_width     2 non-null      object
 18  osm_id_index  73332 non-null  int64
dtypes: bool(1), float64(1), geometry(1), int64(1), object(15)
memory usage: 10.1+ MB

,osmid,highway,lanes,maxspeed,name,oneway,reversed,length,geometry,width,ref,bridge,tunnel,junction,access,area,service,est_width,osm_id_index
0,"[33231778, 31740296, 4804202, 1119769231, 1119...",secondary,"[3, 2, 1]",50,Gotthardstraße,False,False,436.953782,"LINESTRING (387179.764 5825206.839, 387173.255...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,"[5117633, 1387012309, 1387012310, 1387012318, ...",secondary,2,50,Gotthardstraße,False,True,687.378984,"LINESTRING (387179.764 5825206.839, 387186.953...",13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,"[1188446056, 1188446055, 4610047, 1391160895]",tertiary,2,50,Holländerstraße,False,False,240.923771,"LINESTRING (387179.764 5825206.839, 387184.466...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,24973218,tertiary,NaN,50,Teichstraße,False,False,17.178731,"LINESTRING (387937.322 5825392.37, 387939.154 ...",15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,40817055,secondary,2,50,Gotthardstraße,True,False,103.173716,"LINESTRING (387937.322 5825392.37, 387930.389 ...",9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [21]:
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["traffic_dashboard"]
collection = db["road_kpi_snapshots"]

print("Total documents:", collection.count_documents({}))

Total documents: 4464

In [8]:
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["traffic_dashboard"]
print(db.list_collection_names())

['road_kpi_snapshots']

In [27]:
from pymongo import MongoClient

client = MongoClient("mongodb://root:Hohoang0403#@mongo-berlin-traffic.captain.dev.huyhoangho.online:27017/")
db = client["traffic_dashboard"]
collection = db["road_kpi_snapshots"]

print("Total documents:", collection.count_documents({}))

Total documents: 4464

In [24]:
from pymongo import MongoClient

client = MongoClient("mongodb://root:Hohoang0403#@mongo-berlin-traffic.captain.dev.huyhoangho.online:27017/")
client.admin.command('ping')

{'ok': 1.0}